BKM/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path(r'admin/', admin.site.urls),
    url(r'app/', include('app1.urls'))       # 包含APP1中的所有路径映射
]

app1/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    '''
    出版社实体
    '''
    name = models.CharField(max_length=50, null=False)      # 出版社名字


class Author(models.Model):
    '''
    作者实体
    '''
    name = models.CharField(max_length=16, null=False)      # 作者名字


class Book(models.Model):
    '''
    图书实体
    '''
    name = models.CharField(max_length=50, null=False)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)   # CASCADE, PROTECTED, SET(v), SET_DEFAULT, SET_NULL
    authors = models.ManyToManyField(Author)                # 多对多

templates/author/author_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图书管理系统</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/dashboard.css">
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">图书管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                 <li><a href="/app/publisher_list/">出版社列表</a></li>
                <li class="active"><a href="/app/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
                <li><a href="/app/book_list/">图书列表</a></li>
                <li><a href="#">Analytics</a></li>
                <li><a href="#">Export</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">Nav item</a></li>
                <li><a href="">Nav item again</a></li>
                <li><a href="">One more nav</a></li>
                <li><a href="">Another nav item</a></li>
                <li><a href="">More navigation</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">作者列表</h2>
            <div class="table-responsive">
                <div class="panel panel-info">
                    <div class="panel-heading">新增作者</div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="post">
                            <div class="form-group {% if msg %} has-error {% endif %}">
                                <label for="inputEmail3" class="col-sm-2 control-label">作者名称</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="auth_name" placeholder="请输入出版社名称">
                                    <span id="helpBlock2" class="help-block">{{ msg }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-default">保存新增</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/static/plugins/jQuery/jquery1.12.4.js"></script>
<script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/author/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图书管理系统</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/dashboard.css">
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">图书管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="/app/publisher_list/">出版社列表</a></li>
                <li class="active"><a href="/app/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
                <li><a href="/app/book_list/">图书列表</a></li>
                <li><a href="#">Analytics</a></li>
                <li><a href="#">Export</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">Nav item</a></li>
                <li><a href="">Nav item again</a></li>
                <li><a href="">One more nav</a></li>
                <li><a href="">Another nav item</a></li>
                <li><a href="">More navigation</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">作者列表 <a href="/app/author_add/" class="btn btn-info btn-sm">新增作者</a></h2>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>编号</th>
                        <th>作者名称</th>
                        <th>代表作</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for author in authorList %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ author.pk }}</td>
                            <td>{{ author.name }}</td>
                            <td>{% for book in author.book_set.all %}
                                《{{ book.name }}》
                            {% endfor %}
                            </td>
                            <td>
                                <a class="btn-primary btn-sm" href="/app/author_update/?pk={{ author.pk }}">编辑</a>
                                <a class="btn-danger btn-sm" href="/app/author_delete/?pk={{ author.pk }}">删除</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/static/plugins/jQuery/jquery1.12.4.js"></script>
<script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/author/author_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图书管理系统</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/dashboard.css">
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">图书管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="/app/publisher_list/">出版社列表</a></li>
                <li class="active"><a href="/app/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
                <li><a href="/app/book_list/">图书列表</a></li>
                <li><a href="#">Analytics</a></li>
                <li><a href="#">Export</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">Nav item</a></li>
                <li><a href="">Nav item again</a></li>
                <li><a href="">One more nav</a></li>
                <li><a href="">Another nav item</a></li>
                <li><a href="">More navigation</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">作者列表</h2>
            <div class="table-responsive">
                <div class="panel panel-info">
                    <div class="panel-heading">修改作者</div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="post">
                            <div class="form-group {% if msg %} has-error {% endif %}">
                                <label for="inputEmail3" class="col-sm-2 control-label">出版社名称</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="auth_name" value="{{ auth_obj.name }}" placeholder="请输入出版社名称">
                                    <span id="helpBlock2" class="help-block">{{ msg }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-default">保存修改</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/static/plugins/jQuery/jquery1.12.4.js"></script>
<script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>